### ISSUE TITLE
将 API_COSAPI_END_POINT  修改为支持 https 之后，上传中出现错误

### ISSUE THREAD

**Issue by piratf** [tencentyun/cos-php-sdk-v4#14]
错误内容
日志中记录的报错内容为：

ErrorException: curl_setopt(): CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead in somefile.php:line number

**Comment by yaozongyou** [comment]
能提供下你的php的版本以及操作系统的版本吗？

**Comment by piratf** [comment]
PHP 版本
php -v
PHP 7.1.0 (cli) (built: Jan 10 2017 21:27:14) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies

操作系统版本：
uname -a
Linux VM_53_37_centos 3.10.0-327.28.2.el7.x86_64 #1 SMP Wed Aug 3 11:11:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ACTom** [comment]
这个错误发生是因为在libcurl库在7.28.1中移除了CURLOPT_SSL_VERIFYHOST属性为1的值，只与系统带的libcurl库有关，与php及操作系统版本无关。

可修改src/qcloud/cos/HttpClient.php:83为curl_setopt($this->curlHandler, CURLOPT_SSL_VERIFYHOST, 0);       //do not check

**Comment by piratf** [comment]
我试了一下我的环境确实符合条件，这里改动之后就可以正常运行了，谢谢你！
