### ISSUE TITLE
支持composer了吗？

### ISSUE THREAD

**Issue by server-go** [tencentyun/cos-php-sdk-v4#19]
用composer怎么安装啊？

**Comment by yaozongyou** [comment]
代码结构上已经支持composer了， 由于 https://packagist.org/ 账号相关的问题还没有提交到这里。 麻烦你先通过include的方式来进行使用吧。

**Comment by ACTom** [comment]
不嫌麻烦，可以在composer.json的repositories下添加：
```
  {
      "type": "git",
      "url": "https://github.com/tencentyun/cos-php-sdk-v4.git"
    }
```
然后在 require 下添加
`"qcloud/cos": "dev-master"`

**Comment by ACTom** [comment]
现在已经支持了，包名：qcloud/cos-sdk-v4

**Comment by static7** [comment]
$bucket 这个变量还是不够灵活，还是要每次都要自己传入
我这样改造一下
` /**
     * 设置储存桶名称
     * @author staitc7 <static7@qq.com>
     * @param null $name 储存桶名称
     * @return mixed
     */
    public function setBucket($name = null)
    {
        if (empty($name)){
            return false;
        }
        return $this->bucket=$name;
    }

    /**
     * 获取储存桶名称
     * @author staitc7 <static7@qq.com>
     * @return mixed
     */
    public function getBucket()
    {
        return $this->bucket;
    }`

**Comment by guoyanjun5** [comment]
Good!
