### ISSUE TITLE
我就想知道这个SDK你测试了没有

### ISSUE THREAD

**Issue by CalvinQiang** [tencentyun/cos-php-sdk-v4#2]
sample.php中表示Bucket的$bucket填写正确的名称居然一直返回ERROR_CMD_BUCKET_NOTEXIST,我测试了几遍发现一定要在前面加个空格,比如正常是这样写$bucket = 'test';但是你这个一定要这样写 $bucket = ' test';(前面要加个空格) 难道是你们网站界面创建Bucket的时候前面自动给我加了个空格?说好的trim呢? 然鹅还是会报错,说Missing required header for this request: Appid ,妈蛋,配置好你的conf.php不是应该自动给我添加么.好吧,我用postman手工加了header信息,加了Appid的值,然鹅还是报Missing required header for this request: Appid,求解,你们这是测试版,还是啥版本,是我太坑,还是你们太坑?

**Comment by yaozongyou** [comment]
您好，你的appid和bucket是多少？我这些查询下，谢谢。

**Comment by yaozongyou** [comment]
conf.php配置好后，Appid是会自动加的，我看下你这个case哈，麻烦发下appid和bucket的信息。

**Comment by CalvinQiang** [comment]
Bucket: testupdate 
appid: 1252880649


遗忘好久了=。=




在 2016-12-07 16:09:12，"Yao Zongyou" <notifications@github.com> 写道：


Closed #2.

**Comment by bytehello** [comment]
应该是你的region填写出问题了
枚举值见 -> https://www.qcloud.com/document/product/436/6273#.E5.88.9D.E5.A7.8B.E5.8C.96.E5.AE.A2.E6.88.B7.E7.AB.AF.E9.85.8D.E7.BD.AE(.E5.A6.82.E8.AE.BE.E7.BD.AE.E5.9B.AD.E5.8C.BA)9
