### ISSUE TITLE
$bucket 这个变量还是不够灵活啊，每次都要传入

### ISSUE THREAD

**Issue by static7** [tencentyun/cos-php-sdk-v4#24]
每次都要传入储存桶bucket的名称，感觉很麻烦
我这样改一下
定义
    private $bucket; //储存桶名称
设置和获取

     /**
     * 设置储存桶名称
     * @author staitc7 <static7@qq.com>
     * @param null $name 储存桶名称
     * @return mixed
     */
    public function setBucket($name = null)
    {
        if (empty($name)){
            return false;
        }
        return $this->bucket=$name;
    } 
    /**
     * 获取储存桶名称
     * @author staitc7 <static7@qq.com>
     * @return mixed
     */
    public function getBucket()
    {
        return $this->bucket;
    }  

然后实例化后设置一次就行了

**Comment by ACTom** [comment]
你可以自己做个再封装的，但是我个人不建议修改这个项目，不然所有api都与当前版本的不兼容了，5.x版做这个调整倒是挺好的

**Comment by tinpont** [comment]
你说的是你个人的使用情况，作为SDK，提供的接口应该以全面为主。试想一下，假如我有一个文件要同时备份到五个bucket该怎么办。
