### ISSUE TITLE
不做composer.json加载吗？什么年代了

### ISSUE THREAD

**Issue by hinet** [tencentyun/cos-php-sdk-v4#6]

**Comment by simaguo** [comment]
+111111111111111111111111111111111111111111111111111
感觉吃了一坨屎

**Comment by yaozongyou** [comment]
感谢您的关注，会尽快加上！
另外，欢迎提pull request.

**Comment by tinpont** [comment]
+1，希望尽快加上，方便开发者开发其他框架的集成。

**Comment by hinet** [comment]
这尽快，几个月都过去了还没进度呢？

**Comment by tinpont** [comment]
唉，看到还在用这个静态变量赋值key什么的就难受，这样让有多个bucket、api key的人怎么操作。封装成一个类就这么难吗？

**Comment by hinet** [comment]
腾讯团队也这么低效吗？

**Comment by codedart2018** [comment]
哈哈 一年了，居然还是这个鸟样，没有集成到composer里面去

**Comment by mclxly** [comment]
https://packagist.org 已经有一些封装了，我自己也弄了个，增加了上传指定目录的接口。

composer require "mclxly/tencentyun-cos-php:dev-master"

**Comment by ACTom** [comment]
目前代码已经支持composer了，只是packagist.org上qcloud域的作者联系不上，暂时可采用git方式引用。
